development:
  adapter: postgresql
  host: ec2-184-73-165-193.compute-1.amazonaws.com
  database: d5npa1bm5t8077
  user: cwnptitginhbpz
  port: 5432
  password: D8QxM7OByIfPJ-3rEKrmIbZrWl
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  host: ec2-184-73-165-193.compute-1.amazonaws.com
  database: d5npa1bm5t8077
  user: cwnptitginhbpz
  port: 5432
  password: D8QxM7OByIfPJ-3rEKrmIbZrWl
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: ec2-184-73-165-193.compute-1.amazonaws.com
  database: d5npa1bm5t8077
  user: cwnptitginhbpz
  port: 5432
  password: D8QxM7OByIfPJ-3rEKrmIbZrWl
  pool: 5
  timeout: 5000